
server:
  port: 10006
weather:
  url: http://wthrcdn.etouch.cn/weather_mini?
spring:
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
