
server:
  port: 10006
weather:
  url: http://wthrcdn.etouch.cn/weather_mini?
  name: msa-weather-data-server-api
city:
  name: msa-weather-city-collection-api
spring:
  thymeleaf:
    cache: false
  application:
    name: msa-weather-report-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
  httpclient:
    enabled: true
