
server:
  port: 10006
weather:
  url: http://wthrcdn.etouch.cn/weather_mini?
spring:
  thymeleaf:
    cache: false
  application:
    name: msa-weather-report-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}

