
server:
  port: 10008
spring:
  application:
    name: msa-weather-gateway-api
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    weather:
      path: /weather/**
      serviceId: msa-weather-data-server-api
    city:
      path: /city/**
      serviceId: msa-weather-city-collection-api
  host:
    connect-timeout-millis: 600000
    connection-request-timeout-millis: 600000
ribbon:
  eureka:
    enabled: true

